sudo: required
dist: trusty
language: php
php:
  - '7.1'

env:
  - TRAVIS_NODE_VERSION="8.3.0"

services:
  - mysql

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version

install:
  - npm install
  - cp .env.travis .env
  - composer install
  - ./travis-setup-db.sh
  - php -S 0.0.0.0:8888 -t ./ >& /dev/null &

script:
  - npm run test:e2e:all
  - npm run test:unit