nginx:
  image: prooph/nginx:www
  ports:
      - "8080:80"
      - "443:443"
  links:
    - php:php
  volumes_from:
    - dataphp

php:
  image: prooph/php:7.0-fpm
  links:
    - mariadb:mariadb
  volumes_from:
    - dataphp

dataphp:
  image: debian:jessie
  volumes:
    - ./:/var/www/public

mariadb:
  build: ./docker/mysql
  ports:
    - "3306:3306"
  volumes:
    - ./docker/data-volume:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=dev
    - MYSQL_USER=dev
    - MYSQL_PASSWORD=dev
    - MYSQL_DATABASE=prooph
